[package]
name = "pretty_size"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
clap = "3.0.0-beta.4"
serde_json = "1.0"
hex = "0.4.3"